version: '3'

services:
    tests:
        container_name: tests
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/code
        working_dir: /code
        depends_on:
            - mongodb
            - mongo_repl_init
            - mysql
        stdin_open: true
        tty: true

    mysql:
        container_name: mysql
        image: mysql:5.7
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD:
            MYSQL_DATABASE: unittest
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        logging:
            driver: none

    mongodb:
        container_name: mongodb
        image: mongo:6.0
        ports:
            - "27017:27017"
        entrypoint: [ "/usr/bin/mongod", "--quiet", "--bind_ip_all", "--replSet", "rs" ]
        logging:
            driver: none

    mongo_repl_init:
        image: mongo:6.0
        depends_on:
            - mongodb
        environment:
            - RS=rs
        volumes:
            - ./:/scripts
        entrypoint: [ "sh", "-c", "/scripts/mongo-repl-init.sh" ]
        logging:
            driver: none
